# Generated by Django 5.2.16 on 2026-07-11 13:42

import django.core.validators
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('download_speed_mbps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('grace_period_hours', models.PositiveIntegerField(default=24)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['download_speed_mbps', 'price_minor', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='billing_plan_name_ci_unique'), models.CheckConstraint(condition=models.Q(('download_speed_mbps__gt', 0)), name='billing_plan_download_speed_positive'), models.CheckConstraint(condition=models.Q(('price_minor__gt', 0)), name='billing_plan_price_positive'), models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='billing_plan_currency_kes'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='billing_plan_duration_positive'), models.CheckConstraint(condition=models.Q(('grace_period_hours__gte', 0)), name='billing_plan_grace_non_negative')],
            },
        ),
    ]
