# Generated by Django 5.2.16 on 2026-07-12 02:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription'),
        ('subscribers', '0003_alter_service_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('period_type', models.CharField(choices=[('activation', 'Activation'), ('renewal', 'Renewal')], max_length=12)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('effective_at', models.DateTimeField()),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('grace_until', models.DateTimeField()),
                ('plan_name', models.CharField(max_length=120)),
                ('download_speed_mbps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grace_period_hours', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_periods', to='billing.billingperiod')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_periods', to='subscribers.service')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_periods', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Billing period',
                'verbose_name_plural': 'Billing periods',
                'ordering': ['service', '-sequence_number'],
                'indexes': [models.Index(fields=['service', 'sequence_number'], name='billing_period_service_seq_idx'), models.Index(fields=['service', 'expires_at'], name='billing_period_service_exp_idx'), models.Index(fields=['subscription'], name='billing_period_sub_idx'), models.Index(fields=['operation_id'], name='billing_period_operation_idx')],
                'constraints': [models.UniqueConstraint(fields=('service', 'sequence_number'), name='billing_period_service_sequence_unique'), models.UniqueConstraint(condition=models.Q(('previous_period__isnull', False)), fields=('previous_period',), name='billing_period_previous_single_successor'), models.CheckConstraint(condition=models.Q(('sequence_number__gt', 0)), name='billing_period_sequence_positive'), models.CheckConstraint(condition=models.Q(('period_type__in', ['activation', 'renewal'])), name='billing_period_type_valid'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='billing_period_expires_after_start'), models.CheckConstraint(condition=models.Q(('grace_until__gte', models.F('expires_at'))), name='billing_period_grace_after_expiry'), models.CheckConstraint(condition=models.Q(('price_minor__gt', 0)), name='billing_period_price_positive'), models.CheckConstraint(condition=models.Q(('download_speed_mbps__gt', 0)), name='billing_period_download_positive'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='billing_period_duration_positive'), models.CheckConstraint(condition=models.Q(('grace_period_hours__gte', 0)), name='billing_period_grace_non_negative'), models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='billing_period_currency_kes'), models.CheckConstraint(condition=models.Q(models.Q(('period_type', 'activation'), ('previous_period__isnull', True)), models.Q(('period_type', 'renewal'), ('previous_period__isnull', False)), _connector='OR'), name='billing_period_previous_matches_type')],
            },
        ),
    ]
