# Generated by Django 5.2.16 on 2026-07-12 13:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingperiod'),
        ('subscribers', '0003_alter_service_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['subscriber__account_number'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('operation_id', models.UUIDField(editable=False, unique=True)),
                ('entry_type', models.CharField(choices=[('manual_credit', 'Manual credit'), ('manual_debit', 'Manual debit'), ('reversal', 'Reversal')], max_length=20)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)])),
                ('balance_after_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)])),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('previous_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_entries', to='billing.ledgerentry')),
                ('reverses_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='billing.ledgerentry')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='billing.wallet')),
            ],
            options={
                'verbose_name': 'Ledger entry',
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['wallet', '-sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['subscriber'], name='billing_wallet_subscriber_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='billing_wallet_currency_kes'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', 'sequence_number'], name='ledger_entry_wallet_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', 'created_at'], name='ledger_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['operation_id'], name='ledger_entry_operation_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type'], name='ledger_entry_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reverses_entry'], name='ledger_entry_reverses_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('wallet', 'sequence_number'), name='ledger_entry_wallet_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_entry__isnull', False)), fields=('previous_entry',), name='ledger_entry_previous_single_successor'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_number__gt', 0)), name='ledger_entry_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='ledger_entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after_minor__gte', 0)), name='ledger_entry_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='ledger_entry_currency_kes'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['manual_credit', 'manual_debit', 'reversal'])), name='ledger_entry_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['credit', 'debit'])), name='ledger_entry_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('previous_entry__isnull', True), ('sequence_number', 1)), models.Q(('previous_entry__isnull', False), ('sequence_number__gt', 1)), _connector='OR'), name='ledger_entry_previous_matches_sequence'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type__in', ['manual_credit', 'manual_debit']), ('reverses_entry__isnull', True)), models.Q(('entry_type', 'reversal'), ('reverses_entry__isnull', False)), _connector='OR'), name='ledger_entry_reversal_matches_type'),
        ),
    ]
