# Generated by Django 5.2.16 on 2026-07-12 16:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_wallet_ledgerentry_and_more'),
        ('subscribers', '0003_alter_service_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(editable=False, unique=True)),
                ('charge_type', models.CharField(choices=[('activation', 'Activation'), ('renewal', 'Renewal')], max_length=12)),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)])),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billing charge',
                'verbose_name_plural': 'Billing charges',
                'ordering': ['service', '-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledger_entry_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledger_entry_reversal_matches_type',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('manual_credit', 'Manual credit'), ('manual_debit', 'Manual debit'), ('billing_charge', 'Billing charge'), ('reversal', 'Reversal')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['manual_credit', 'manual_debit', 'billing_charge', 'reversal'])), name='ledger_entry_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'credit'), ('entry_type', 'manual_credit')), models.Q(('direction', 'debit'), ('entry_type', 'manual_debit')), models.Q(('direction', 'debit'), ('entry_type', 'billing_charge')), ('entry_type', 'reversal'), _connector='OR'), name='ledger_entry_type_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type__in', ['manual_credit', 'manual_debit', 'billing_charge']), ('reverses_entry__isnull', True)), models.Q(('entry_type', 'reversal'), ('reverses_entry__isnull', False)), _connector='OR'), name='ledger_entry_reversal_matches_type'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='billing_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_charge', to='billing.billingperiod'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_billing_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='ledger_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_charge', to='billing.ledgerentry'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_charges', to='subscribers.service'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_charges', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_charges', to='billing.wallet'),
        ),
        migrations.AddIndex(
            model_name='billingcharge',
            index=models.Index(fields=['service', 'charge_type'], name='bill_charge_service_type_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcharge',
            index=models.Index(fields=['wallet', 'created_at'], name='bill_charge_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcharge',
            index=models.Index(fields=['operation_id'], name='billing_charge_operation_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingcharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='billing_charge_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingcharge',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='billing_charge_currency_kes'),
        ),
        migrations.AddConstraint(
            model_name='billingcharge',
            constraint=models.CheckConstraint(condition=models.Q(('charge_type__in', ['activation', 'renewal'])), name='billing_charge_type_valid'),
        ),
    ]
