# Generated by Django 5.2.16 on 2026-07-12 20:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_fake_payment_profile(apps, _schema_editor):
    profile_model = apps.get_model('billing', 'PaymentProviderProfile')
    profile_model.objects.get_or_create(
        provider='fake',
        product_type='fake',
        environment='test',
        external_identifier='fake-test',
        defaults={
            'name': 'SuperSurf Fake Test Provider',
            'is_active': True,
        },
    )


def unseed_fake_payment_profile(apps, _schema_editor):
    profile_model = apps.get_model('billing', 'PaymentProviderProfile')
    profile_model.objects.filter(
        provider='fake',
        product_type='fake',
        environment='test',
        external_identifier='fake-test',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billingcharge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_transaction_id', models.CharField(max_length=128)),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)])),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('received_at', models.DateTimeField()),
                ('account_reference', models.CharField(blank=True, max_length=64)),
                ('payload_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-received_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(editable=False, unique=True)),
                ('allocation_type', models.CharField(choices=[('wallet_credit', 'Wallet credit')], default='wallet_credit', editable=False, max_length=20)),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)])),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment allocation',
                'verbose_name_plural': 'Payment allocations',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('fake', 'Fake'), ('mpesa', 'M-PESA')], max_length=12)),
                ('product_type', models.CharField(choices=[('fake', 'Fake'), ('paybill', 'Paybill'), ('till', 'Till')], max_length=12)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('sandbox', 'Sandbox'), ('production', 'Production')], max_length=12)),
                ('external_identifier', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment provider profile',
                'verbose_name_plural': 'Payment provider profiles',
                'ordering': ['provider', 'product_type', 'environment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedPaymentCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('reason_code', models.CharField(choices=[('missing_reference', 'Missing reference'), ('invalid_reference', 'Invalid reference'), ('subscriber_not_found', 'Subscriber not found')], max_length=32)),
                ('resolution_reason', models.CharField(blank=True, max_length=240)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unmatched payment case',
                'verbose_name_plural': 'Unmatched payment cases',
                'ordering': ['status', '-opened_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledger_entry_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledger_entry_type_direction_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledger_entry_reversal_matches_type',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('manual_credit', 'Manual credit'), ('manual_debit', 'Manual debit'), ('billing_charge', 'Billing charge'), ('payment_credit', 'Payment credit'), ('reversal', 'Reversal')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['manual_credit', 'manual_debit', 'billing_charge', 'payment_credit', 'reversal'])), name='ledger_entry_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'credit'), ('entry_type', 'manual_credit')), models.Q(('direction', 'debit'), ('entry_type', 'manual_debit')), models.Q(('direction', 'debit'), ('entry_type', 'billing_charge')), models.Q(('direction', 'credit'), ('entry_type', 'payment_credit')), ('entry_type', 'reversal'), _connector='OR'), name='ledger_entry_type_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type__in', ['manual_credit', 'manual_debit', 'billing_charge']), ('reverses_entry__isnull', True)), models.Q(('entry_type', 'payment_credit'), ('reverses_entry__isnull', True)), models.Q(('entry_type', 'reversal'), ('reverses_entry__isnull', False)), _connector='OR'), name='ledger_entry_reversal_matches_type'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='ledger_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocation', to='billing.ledgerentry'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.wallet'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderprofile',
            constraint=models.UniqueConstraint(fields=('provider', 'product_type', 'environment', 'external_identifier'), name='payment_provider_profile_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderprofile',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['fake', 'mpesa'])), name='payment_provider_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderprofile',
            constraint=models.CheckConstraint(condition=models.Q(('product_type__in', ['fake', 'paybill', 'till'])), name='payment_provider_product_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderprofile',
            constraint=models.CheckConstraint(condition=models.Q(('environment__in', ['test', 'sandbox', 'production'])), name='payment_provider_environment_valid'),
        ),
        migrations.RunPython(seed_fake_payment_profile, unseed_fake_payment_profile),
        migrations.AddField(
            model_name='payment',
            name='provider_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.paymentproviderprofile'),
        ),
        migrations.AddField(
            model_name='unmatchedpaymentcase',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='unmatched_case', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='unmatchedpaymentcase',
            name='resolution_allocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_unmatched_case', to='billing.paymentallocation'),
        ),
        migrations.AddField(
            model_name='unmatchedpaymentcase',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_unmatched_payment_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unmatchedpaymentcase',
            name='resolved_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_unmatched_payment_cases', to='billing.wallet'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='payment_allocation_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['wallet', 'created_at'], name='pay_alloc_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['operation_id'], name='payment_alloc_operation_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment',), name='one_allocation_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_type', 'wallet_credit')), name='payment_allocation_type_wallet'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='payment_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='payment_allocation_currency_kes'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_profile', 'provider_transaction_id'], name='payment_provider_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account_reference'], name='payment_account_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['received_at'], name='payment_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('provider_profile', 'provider_transaction_id'), name='payment_provider_transaction_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='payment_currency_kes'),
        ),
        migrations.AddIndex(
            model_name='unmatchedpaymentcase',
            index=models.Index(fields=['status', 'opened_at'], name='unmatched_status_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='unmatchedpaymentcase',
            index=models.Index(fields=['reason_code'], name='unmatched_case_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='unmatchedpaymentcase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'resolved'])), name='unmatched_case_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='unmatchedpaymentcase',
            constraint=models.CheckConstraint(condition=models.Q(('reason_code__in', ['missing_reference', 'invalid_reference', 'subscriber_not_found'])), name='unmatched_case_reason_valid'),
        ),
    ]
