# Generated by Django 5.2.16 on 2026-07-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_payment_paymentallocation_paymentproviderprofile_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), name='payment_provider_transaction_nonblank'),
        ),
    ]
