# Generated by Django 5.2.16 on 2026-07-13 22:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment_payment_provider_transaction_nonblank'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('c2b_validation', 'C2B validation'), ('c2b_confirmation', 'C2B confirmation'), ('stk_result', 'STK result')], max_length=24)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('sanitized_payload', models.JSONField()),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128)),
                ('merchant_request_id', models.CharField(blank=True, max_length=128)),
                ('checkout_request_id', models.CharField(blank=True, max_length=128)),
                ('account_reference', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('result_code', models.CharField(blank=True, max_length=16)),
                ('result_description', models.CharField(blank=True, max_length=240)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-PESA callback event',
                'verbose_name_plural': 'M-PESA callback events',
                'ordering': ['-received_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type', 'received_at'], name='mpesa_cb_event_type_recv_idx'), models.Index(fields=['provider_transaction_id'], name='mpesa_cb_provider_tx_idx'), models.Index(fields=['merchant_request_id'], name='mpesa_cb_merchant_req_idx'), models.Index(fields=['checkout_request_id'], name='mpesa_cb_checkout_req_idx'), models.Index(fields=['account_reference'], name='mpesa_cb_account_ref_idx'), models.Index(fields=['result_code'], name='mpesa_cb_result_code_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['c2b_validation', 'c2b_confirmation', 'stk_result'])), name='mpesa_callback_event_type_valid'), models.CheckConstraint(condition=models.Q(('payload_sha256__regex', '^[0-9a-f]{64}$')), name='mpesa_callback_payload_sha256_hex'), models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='mpesa_callback_idempotency_nonblank'), models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='mpesa_callback_amount_positive')],
            },
        ),
    ]
