# Generated by Django 5.2.16 on 2026-07-17 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_mpesacallbackevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackPaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-PESA callback payment link',
                'verbose_name_plural': 'M-PESA callback payment links',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='creation_source',
            field=models.CharField(choices=[('operator', 'Operator'), ('system', 'System')], default='operator', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='mpesacallbackevent',
            name='provider_external_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='creation_source',
            field=models.CharField(choices=[('operator', 'Operator'), ('system', 'System')], default='operator', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_by__isnull', False), ('creation_source', 'operator')), models.Q(('created_by__isnull', True), ('creation_source', 'system')), _connector='OR'), name='ledger_entry_source_actor_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('creation_source', 'operator'), models.Q(('creation_source', 'system'), ('entry_type', 'payment_credit')), _connector='OR'), name='ledger_entry_system_payment_only'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_by__isnull', False), ('creation_source', 'operator')), models.Q(('created_by__isnull', True), ('creation_source', 'system')), _connector='OR'), name='payment_allocation_source_actor_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product_type', 'fake'), ('provider', 'fake')), models.Q(('product_type__in', ['paybill', 'till']), ('provider', 'mpesa')), _connector='OR'), name='payment_provider_product_pair_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('provider', 'mpesa')), fields=('product_type', 'environment'), name='one_active_mpesa_product_environment'),
        ),
        migrations.AddField(
            model_name='mpesacallbackpaymentlink',
            name='callback_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_link', to='billing.mpesacallbackevent'),
        ),
        migrations.AddField(
            model_name='mpesacallbackpaymentlink',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_callback_link', to='billing.payment'),
        ),
    ]
