# Generated by Django 5.2.16 on 2026-07-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_brand', models.CharField(default='SuperSurf', max_length=120)),
                ('trading_name', models.CharField(default='SuperSurf', max_length=120)),
                ('product_name', models.CharField(default='SuperSurf Billing', max_length=120)),
                ('network_label', models.CharField(default='SuperSurf Networks', max_length=120)),
                ('support_label', models.CharField(default='SuperSurf Support', max_length=120)),
                ('portal_label', models.CharField(default='SuperSurf Portal', max_length=120)),
                ('registered_business_name', models.CharField(blank=True, max_length=180)),
                ('domain', models.CharField(blank=True, max_length=180)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('noc_email', models.EmailField(blank=True, max_length=254, verbose_name='NOC email')),
                ('support_phone', models.CharField(blank=True, max_length=40)),
                ('paybill_number', models.CharField(blank=True, max_length=40)),
                ('till_number', models.CharField(blank=True, max_length=40)),
                ('kra_pin', models.CharField(blank=True, max_length=40, verbose_name='KRA PIN')),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('communications_authority_licence', models.CharField(blank=True, max_length=180)),
                ('country', models.CharField(default='Kenya', max_length=80)),
                ('country_code', models.CharField(default='KE', max_length=2)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('currency_display_label', models.CharField(default='KSh', max_length=12)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=80)),
                ('locale', models.CharField(default='en-KE', max_length=20)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(default='24-hour', max_length=20)),
                ('week_start', models.CharField(default='Monday', max_length=20)),
                ('telephone_country_code', models.CharField(default='+254', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('view_sensitive_settings', 'Can view sensitive settings'), ('change_sensitive_settings', 'Can change sensitive settings'), ('run_production_readiness_checks', 'Can run production readiness checks')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='branding/')),
                ('favicon', models.FileField(blank=True, upload_to='branding/')),
                ('primary_ui_colour', models.CharField(default='#075985', max_length=20)),
                ('secondary_ui_colour', models.CharField(default='#15803d', max_length=20)),
                ('receipt_heading', models.CharField(default='SuperSurf Billing', max_length=160)),
                ('invoice_heading', models.CharField(default='SuperSurf Billing', max_length=160)),
                ('receipt_footer', models.TextField(blank=True)),
                ('invoice_footer', models.TextField(blank=True)),
                ('payment_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='core.organization')),
            ],
        ),
    ]
