# Generated by Django 5.2.16 on 2026-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=120)),
                ('target_identifier', models.CharField(blank=True, max_length=160)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(default='success', max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_security_audit', 'Can view security audit events')],
            },
        ),
    ]
