from __future__ import annotations

ROLE_OWNER = "Owner"
ROLE_ADMINISTRATOR = "Administrator"
ROLE_FINANCE = "Finance"
ROLE_NOC = "NOC"
ROLE_SUPPORT = "SuperSurf Support"
ROLE_READ_ONLY = "Read Only"

ROLE_NAMES = [
    ROLE_OWNER,
    ROLE_ADMINISTRATOR,
    ROLE_FINANCE,
    ROLE_NOC,
    ROLE_SUPPORT,
    ROLE_READ_ONLY,
]

ROLE_PERMISSION_CODENAMES = {
    ROLE_OWNER: ["*"],
    ROLE_ADMINISTRATOR: [
        "core.view_organization",
        "core.change_organization",
        "core.view_organizationbranding",
        "core.change_organizationbranding",
        "users.view_user",
        "users.change_user",
        "users.assign_roles",
        "audit.view_auditevent",
        "billing.view_plan",
        "billing.add_plan",
        "billing.change_plan",
        "billing.view_subscription",
        "billing.add_subscription",
        "billing.change_subscription",
        "billing.view_billingperiod",
        "billing.add_billingperiod",
        "billing.view_billingcharge",
        "billing.add_billingcharge",
        "billing.view_paymentproviderprofile",
        "billing.add_paymentproviderprofile",
        "billing.view_payment",
        "billing.add_payment",
        "billing.view_paymentallocation",
        "billing.add_paymentallocation",
        "billing.view_unmatchedpaymentcase",
        "billing.change_unmatchedpaymentcase",
        "billing.view_mpesacallbackevent",
        "billing.view_wallet",
        "billing.view_ledgerentry",
        "billing.add_ledgerentry",
        "subscribers.view_subscriber",
        "subscribers.add_subscriber",
        "subscribers.change_subscriber",
        "subscribers.view_service",
        "subscribers.add_service",
        "subscribers.change_service",
    ],
    ROLE_FINANCE: [
        "core.view_organization",
        "core.view_organizationbranding",
        "audit.view_auditevent",
        "billing.view_plan",
        "billing.view_subscription",
        "billing.view_billingperiod",
        "billing.add_billingperiod",
        "billing.view_billingcharge",
        "billing.add_billingcharge",
        "billing.view_paymentproviderprofile",
        "billing.add_paymentproviderprofile",
        "billing.view_payment",
        "billing.add_payment",
        "billing.view_paymentallocation",
        "billing.add_paymentallocation",
        "billing.view_unmatchedpaymentcase",
        "billing.change_unmatchedpaymentcase",
        "billing.view_mpesacallbackevent",
        "billing.view_wallet",
        "billing.view_ledgerentry",
        "billing.add_ledgerentry",
        "subscribers.view_subscriber",
        "subscribers.view_service",
    ],
    ROLE_NOC: [
        "core.view_organization",
        "core.view_organizationbranding",
        "audit.view_auditevent",
        "billing.view_plan",
        "billing.view_subscription",
        "billing.view_billingperiod",
        "subscribers.view_subscriber",
        "subscribers.view_service",
    ],
    ROLE_SUPPORT: [
        "core.view_organization",
        "core.view_organizationbranding",
        "users.view_user",
        "billing.view_plan",
        "billing.view_subscription",
        "billing.view_billingperiod",
        "billing.view_billingcharge",
        "billing.view_payment",
        "billing.view_paymentallocation",
        "billing.view_unmatchedpaymentcase",
        "billing.view_wallet",
        "billing.view_ledgerentry",
        "subscribers.view_subscriber",
        "subscribers.view_service",
    ],
    ROLE_READ_ONLY: [
        "core.view_organization",
        "core.view_organizationbranding",
        "users.view_user",
        "audit.view_auditevent",
        "billing.view_plan",
        "billing.view_subscription",
        "billing.view_billingperiod",
        "billing.view_billingcharge",
        "billing.view_payment",
        "billing.view_paymentallocation",
        "billing.view_unmatchedpaymentcase",
        "billing.view_wallet",
        "billing.view_ledgerentry",
        "subscribers.view_subscriber",
        "subscribers.view_service",
    ],
}


def is_owner(user) -> bool:
    return bool(user and user.is_authenticated and user.groups.filter(name=ROLE_OWNER).exists())
